version: 43
jobs:
- name: Push to Github
  steps:
  - type: CheckoutStep
    name: Get Code
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: PushRepository
    name: Push to github
    remoteUrl: https://github.com/Limo123123/teacher-grades
    userName: Limo123123
    passwordSecret: gh
    force: true
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
